### PR TITLE
🐛 Fixed situation with nested compositions where not all properties w…

### PR DESCRIPTION
**Pull request by robertjf**
…ere mapped

@nathanwoulfe when I tried mapping a Document Type to an Inherited Document Type, not all the properties were available to be mapped across.  This change fixes that.

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Magic, thanks Robert. I'll get a release out soon. 

Any appetite to see this working on 14+?

**Comment by robertjf** [comment]
I'm sure I can work that out fairly easily - will jump on it after the Melbourne Meetup tonight

**Comment by nathanwoulfe** [comment]
There isn't a v14 yet - wasn't implying you should do it, more curious as to whether I should jump onto the v14 rebuild

**Comment by robertjf** [comment]
I would - probably more Umbraco 15 :)

**Comment by robertjf** [comment]
@nathanwoulfe any chance we can get a release today? I have a project held up due to this...

🙏

**Comment by nathanwoulfe** [comment]
Hey @robertjf I'm currently lazing on the beach at Cabarita, heading home tomorrow morning. I'll get it sorted when I return to the real world

**Comment by nathanwoulfe** [comment]
@robertjf merged, packed and pushed to Nuget, should be available shortly.

**Pull request merged**
